{{ if $.Values.alertmanager.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" $ }}-slack
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
stringData:
  webhook_url: {{ $.Values.alertmanager.slack.url | required "slack url is required" }}
{{- end }}
